import Head from 'next/head'
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

function expectStringParameter(parameter: string): string {
  if (typeof parameter !== 'string') {
    throw new Error(`Expected a string parameter, but got ${typeof parameter}`)
  }
  return parameter
}

export default function NamePage() {
  const { name } = useRouter<"/[name]">().query

  const [data, setData] = useState()
  const [isLoading, setIsLoading] = useState(false)
  const [fetchLogs, setFetchLogs] = useState<string[]>([])

  expectStringParameter(name);

  useEffect(() => {
    const fetchURLPath = `/api/hello?name=${name}`
    setFetchLogs(urlLogs => [...urlLogs, fetchURLPath])
    setIsLoading(true)
    fetch(fetchURLPath)
    .then((res) => res.json())
    .then((data) => {
      setData(data.name)
      setIsLoading(false)
    })
  }, [name])

  if (isLoading) return <p>Loading...</p>
  if (!data) return <p>No name</p>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello {data}</h1>
        <p>Fetch logs:</p>
        <ul>
          {fetchLogs.map((url, index) => (
            <li key={index}><code>{url}</code></li>
          ))}
        </ul>
      </main>
    </>
  )
}
